Diagonalisation code for (e)

In [3]:
import numpy as np

# For the first parameter set
V = -1/3
W = -1/4
H = np.array([
    [-2*2, 0, np.sqrt(6)*V, 0, 0],
    [0, -2+3*W, 0, 3*V, 0],
    [np.sqrt(6)*V, 0, 4*W, 0, np.sqrt(6)*V],
    [0, 3*V, 0, 2+3*W, 0],
    [0, 0, np.sqrt(6)*V, 0, 2*2]
])

E, psi = np.linalg.eigh(H)  # eigenvalues and eigenfunctions
print(E)
print(psi)

[-4.2128767  -2.98606798 -0.91913567  1.48606798  4.13201237]
[[ 0.96734848  0.          0.25294303  0.          0.0160235 ]
 [ 0.          0.97324899  0.          0.22975292  0.        ]
 [ 0.25220675  0.         -0.95442304  0.         -0.15958828]
 [ 0.          0.22975292  0.         -0.97324899  0.        ]
 [ 0.02507355  0.         -0.15841871  0.          0.98705361]]


In [4]:
# For the second parameter set
V = -4/3
W = -1
H = np.array([
    [-2*2, 0, np.sqrt(6)*V, 0, 0],
    [0, -2+3*W, 0, 3*V, 0],
    [np.sqrt(6)*V, 0, 4*W, 0, np.sqrt(6)*V],
    [0, 3*V, 0, 2+3*W, 0],
    [0, 0, np.sqrt(6)*V, 0, 2*2]
])

E, psi = np.linalg.eigh(H)  # eigenvalues and eigenfunctions
print(E)
print(psi)


[-7.75122355 -7.47213595 -1.55581365  1.47213595  5.30703721]
[[ 0.6426755   0.          0.75515089  0.          0.12928784]
 [ 0.          0.85065081  0.          0.52573111  0.        ]
 [ 0.73815969  0.         -0.56513693  0.         -0.3684298 ]
 [ 0.          0.52573111  0.         -0.85065081  0.        ]
 [ 0.20515476  0.         -0.33221587  0.          0.9206216 ]]
